# Generated by Django 5.0.3 on 2024-03-15 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='media/poster')),
                ('description', models.CharField(max_length=223)),
                ('is_first', models.BooleanField()),
                ('is_second', models.BooleanField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.storage')),
            ],
        ),
    ]
