# Generated by Django 5.0.3 on 2024-03-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(default=1, upload_to='media/brand'),
            preserve_default=False,
        ),
    ]
